# Generated by Django 5.1.3 on 2024-11-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
